// ══════════════════════════════════════════════
//   DAR SAFIA — CATALOGUE OFFICIEL (45 PARFUMS)
// ══════════════════════════════════════════════
//
// Extrait de main.js pour être importable hors navigateur : main.js exécute
// du code GSAP et DOM au chargement, ce qui empêchait tout script Node
// (migration, seed Strapi) de lire le catalogue.
//
// Ce fichier ne doit contenir QUE des données — aucun import, aucun effet.
export const perfumeCatalog = [
  // ─── FEMME & FLORAUX / GOURMANDS ───
  {
    id: 1,
    name: 'Prada Paradoxe',
    brand: 'Prada',
    gender: 'femme',
    category: 'floral',
    catLabels: ['femme', 'floral', 'amber'],
    price: 23500,
    priceFormatted: '23 500 DA',
    volume: '90ml Eau de Parfum',
    badge: 'Coup de Cœur',
    rating: '4.9',
    reviewsCount: 142,
    desc: "Une célébration de l'expression multidimensionnelle féminine. Un bouquet de fleurs blanches immortalisé par un accord d'ambre chaud et de musc révolutionnaire.",
    story: "Conçu par les maîtres parfumeurs Nadège Le Garlantezec et Antoine Maisondieu, Paradoxe réconcilie la fraîcheur du néroli avec la sensualité d'un ambre exclusif.",
    img: '/img/perfumes/rose.webp',
    top: 'Néroli de Calabre, Bergamote, Mandarine',
    heart: 'Jasmin Sambac, Fleur d’Oranger, Cœur de Néroli',
    base: 'Ambrofix, Musc Blanc Serenolide, Benjoin de Siam',
    longevity: '48h',
    sillage: 'Puissant & Rayonnant',
    concentration: 'Eau de Parfum (22%)'
  },
  {
    id: 2,
    name: 'Prada Paradoxe Intense',
    brand: 'Prada',
    gender: 'femme',
    category: 'floral',
    catLabels: ['femme', 'floral', 'amber'],
    price: 25500,
    priceFormatted: '25 500 DA',
    volume: '90ml Eau de Parfum Intense',
    badge: 'Intense',
    rating: '5.0',
    reviewsCount: 98,
    desc: "L'intensité réinventée. Une signature florale ambrée magnifiée par une surdose de jasmin précieux et une profondeur boisée d'une sensualité captivante.",
    story: "L'expression la plus intense de Paradoxe, où la délicatesse florale rencontre la puissance d'accords ambrés profonds pour une présence inoubliable.",
    img: '/img/perfumes/rose.webp',
    top: 'Essence de Néroli, Bergamote, Accord Poire',
    heart: 'Jasmin Grandiflorum, Accord Mousse, Fleur d’Oranger',
    base: 'Ambrofix, Vanille Bourbon, Accord Boisé Sombre',
    longevity: '48h+',
    sillage: 'Intense & Envoûtant',
    concentration: 'Eau de Parfum Intense (26%)'
  },
  {
    id: 3,
    name: 'Valentino Donna Born In Roma',
    brand: 'Valentino',
    gender: 'femme',
    category: 'floral',
    catLabels: ['femme', 'floral', 'amber'],
    price: 24800,
    priceFormatted: '24 800 DA',
    volume: '100ml Eau de Parfum',
    badge: 'Best Seller',
    rating: '4.9',
    reviewsCount: 215,
    desc: "Une élégance haute couture romaine mêlée à une touche d'audace contemporaine. Trois variétés de jasmin sublimées par une vanille Bourbon d'une rare noblesse.",
    story: "Inspiré par la grandeur éternelle de la cité de Rome et l'esprit rebelle de la haute couture Valentino.",
    img: '/img/perfumes/rose.webp',
    top: 'Cassis, Poivre Rose, Bergamote Italienne',
    heart: 'Jasmin Sambac, Jasmin Grandiflorum, Thé au Jasmin',
    base: 'Vanille Bourbon, Bois de Gaïac, Cachemire',
    longevity: '36h',
    sillage: 'Chic & Remarquable',
    concentration: 'Eau de Parfum (20%)'
  },
  {
    id: 4,
    name: 'Valentino Donna Born In Roma Intense',
    brand: 'Valentino',
    gender: 'femme',
    category: 'amber',
    catLabels: ['femme', 'amber', 'floral'],
    price: 26800,
    priceFormatted: '26 800 DA',
    volume: '100ml Eau de Parfum Intense',
    badge: 'Haute Intensité',
    rating: '4.9',
    reviewsCount: 87,
    desc: "L'ode magnétique aux nuits éternelles de Rome. Une vanille envoûtante s'embrase au contact du benjoin ambré et du jasmin solaire.",
    story: "Une célébration nocturne de la passion romaine dans sa concentration la plus riche et luxueuse.",
    img: '/img/perfumes/amber.webp',
    top: 'Vanille Bourbon, Bergamote Solaire',
    heart: 'Trio de Jasmins Nobles, Accord Floral Nuit',
    base: 'Résine de Benjoin, Bois Précieux',
    longevity: '48h',
    sillage: 'Magnétique',
    concentration: 'Eau de Parfum Intense (25%)'
  },
  {
    id: 5,
    name: 'Rabanne Fame In Love',
    brand: 'Paco Rabanne',
    gender: 'femme',
    category: 'floral',
    catLabels: ['femme', 'floral', 'gourmand'],
    price: 22800,
    priceFormatted: '22 800 DA',
    volume: '80ml Parfum',
    badge: 'Nouveauté',
    rating: '4.8',
    reviewsCount: 76,
    desc: "L'essence irrésistible de la féminité parisienne. Une mangue pulpeuse et succulente mariée à un jasmin d'une clarté lumineuse et un encens addictif.",
    story: "Hommage à l'esprit glamour et avant-gardiste de la maison Rabanne, un sillage fruité-floral d'une gourmandise irrésistible.",
    img: '/img/perfumes/rose.webp',
    top: 'Mangue Sucrée, Bergamote Lumineuse',
    heart: 'Jasmin Lumineux Pur, Fleur d’Encens',
    base: 'Bois de Santal Onctueux, Vanille Noire',
    longevity: '36h',
    sillage: 'Addictif',
    concentration: 'Parfum Concentré'
  },
  {
    id: 6,
    name: 'Lancôme Idôle Peach & Rose',
    brand: 'Lancôme',
    gender: 'femme',
    category: 'floral',
    catLabels: ['femme', 'floral', 'fresh'],
    price: 22800,
    priceFormatted: '22 800 DA',
    volume: '100ml Eau de Parfum',
    badge: 'Élégance',
    rating: '4.8',
    reviewsCount: 164,
    desc: "Un souffle de liberté et de grâce. Une rose moderne infusée de pêche veloutée et de vanille aérienne qui caresse la peau d'une fraîcheur éclatante.",
    story: "Créé par des femmes pour les femmes qui conquièrent leur propre destinée avec douceur et détermination.",
    img: '/img/perfumes/fresh.webp',
    top: 'Pêche Blanche Juteuse, Poire Fondante',
    heart: 'Rose Ispahan Soufflée, Jasmin Pétale',
    base: 'Vanille de Madagascar, Muscs Propres, Cèdre',
    longevity: '36h',
    sillage: 'Lumineux & Propre',
    concentration: 'Eau de Parfum'
  },
  {
    id: 7,
    name: 'Viktor & Rolf Flowerbomb (La Bomba)',
    brand: 'Viktor & Rolf',
    gender: 'femme',
    category: 'floral',
    catLabels: ['femme', 'floral', 'gourmand'],
    price: 21500,
    priceFormatted: '21 500 DA',
    volume: '100ml Eau de Parfum',
    badge: 'Culte',
    rating: '4.9',
    reviewsCount: 310,
    desc: "Une véritable explosion florale opulente et voluptueuse. Des milliers de fleurs transformées en une traînée de charme ensorcelante et gourmande.",
    story: "Le parfum mythique qui a transformé la haute parfumerie en une bombe d'émotions positives et florales.",
    img: '/img/perfumes/ruby.webp',
    top: 'Thé Vert, Bergamote, Osmanthus',
    heart: 'Orchidée Cattleya, Rose Centifolia, Jasmin Sambac',
    base: 'Patchouli Pur, Vanille Gourmande, Musc',
    longevity: '48h',
    sillage: 'Opulent & Inoubliable',
    concentration: 'Eau de Parfum'
  },
  {
    id: 8,
    name: 'Rochas Audace',
    brand: 'Rochas',
    gender: 'femme',
    category: 'floral',
    catLabels: ['femme', 'floral', 'amber'],
    price: 12800,
    priceFormatted: '12 800 DA',
    volume: '100ml Eau de Parfum',
    badge: 'Artisanal',
    rating: '4.7',
    reviewsCount: 52,
    desc: "Le chic parisien incarné avec panache. Un accord chypré floral vintage aux notes riches de prune veloutée, de mousse de chêne et de fleurs d'oranger.",
    story: "L'élégance audacieuse et intemporelle de la haute couture française des années dorées.",
    img: '/img/perfumes/emerald.webp',
    top: 'Fleur d’Oranger, Prune Mirabelle, Bergamote',
    heart: 'Ylang-Ylang, Jasmin Mystique, Rose Poudrée',
    base: 'Mousse de Chêne, Ambre Gris, Bois de Santal',
    longevity: '36h',
    sillage: 'Chic & Vintage',
    concentration: 'Eau de Parfum'
  },
  {
    id: 9,
    name: 'Dolce & Gabbana Devotion (Femme)',
    brand: 'Dolce & Gabbana',
    gender: 'femme',
    category: 'gourmand',
    catLabels: ['femme', 'gourmand', 'fresh'],
    price: 13900,
    priceFormatted: '13 900 DA',
    volume: '100ml Eau de Parfum',
    badge: 'Gourmandise',
    rating: '4.9',
    reviewsCount: 180,
    desc: "Une déclaration d'amour solaire aux racines italiennes. Un citron confit croustillant ouvre la voie à une fleur d'oranger rayonnante et une vanille bourbon onctueuse.",
    story: "Inspiré par le Sacré-Cœur emblématique de D&G, symbole de dévotion inconditionnelle et de passion gourmande.",
    img: '/img/perfumes/ruby.webp',
    top: 'Citron d’Italie Confit, Zestes Sucrés',
    heart: 'Fleur d’Oranger Lumineuse, Panna Cotta',
    base: 'Vanille de Madagascar Précieuse',
    longevity: '36h',
    sillage: 'Solaire & Gourmand',
    concentration: 'Eau de Parfum'
  },
  {
    id: 10,
    name: 'Chloé Le Parfum',
    brand: 'Chloé',
    gender: 'femme',
    category: 'floral',
    catLabels: ['femme', 'floral'],
    price: 21500,
    priceFormatted: '21 500 DA',
    volume: '100ml Le Parfum',
    badge: 'Iconique',
    rating: '4.9',
    reviewsCount: 195,
    desc: "La pure quintessence de la rose Chloé magnifiée à son apogée. Un parfum raffiné, intemporel et follement envoûtant.",
    story: "La liberté d'esprit et l'élégance naturelle de la femme Chloé sublimées par une rose damascena éclatante.",
    img: '/img/perfumes/rose.webp',
    top: 'Litchi Rosé, Pivoine Royale, Freesia',
    heart: 'Rose Damascena Intense, Muguet Frais',
    base: 'Bois de Cèdre de Virginie, Ambre Doré',
    longevity: '36h',
    sillage: 'Poudré & Distingué',
    concentration: 'Le Parfum'
  },
  {
    id: 11,
    name: 'My Burberry Blush',
    brand: 'Burberry',
    gender: 'femme',
    category: 'floral',
    catLabels: ['femme', 'floral', 'fresh'],
    price: 15500,
    priceFormatted: '15 500 DA',
    volume: '90ml Eau de Parfum',
    badge: 'Printemps Éternel',
    rating: '4.8',
    reviewsCount: 88,
    desc: "Inspiré par le premier réveil d'un jardin londonien à l'aube. Une énergie pétillante de grenade givrée et de pétales de rose saupoudrés de rosée.",
    story: "Capturant les premières lueurs du jour sur les jardins royaux de Londres, frais et pétillant.",
    img: '/img/perfumes/rose.webp',
    top: 'Grenade Glacée, Citron Pétillant',
    heart: 'Pétales de Rose, Pomme Verte Croquante, Géranium',
    base: 'Jasmin Blanc, Glycine',
    longevity: '30h',
    sillage: 'Frais & Pétillant',
    concentration: 'Eau de Parfum'
  },
  {
    id: 12,
    name: 'My Burberry (Eau de Parfum)',
    brand: 'Burberry',
    gender: 'femme',
    category: 'floral',
    catLabels: ['femme', 'floral'],
    price: 14800,
    priceFormatted: '14 800 DA',
    volume: '90ml Eau de Parfum',
    badge: 'Classique',
    rating: '4.8',
    reviewsCount: 112,
    desc: "L'icône absolue du trench-coat Burberry en parfum. Un bouquet floral grand style empreint d'une pluie printanière sur des roses de Damas.",
    story: "L'esprit de l'artisanat britannique et du trench-coat iconique, réinterprété en haute parfumerie.",
    img: '/img/perfumes/amber.webp',
    top: 'Pois de Senteur, Bergamote, Mandarine',
    heart: 'Géranium d’Afrique, Freesia, Coing Doré',
    base: 'Rose de Damas, Rose Centifolia, Patchouli',
    longevity: '36h',
    sillage: 'Grand Style',
    concentration: 'Eau de Parfum'
  },
  {
    id: 13,
    name: "Givenchy L'Interdit Rouge",
    brand: 'Givenchy',
    gender: 'femme',
    category: 'amber',
    catLabels: ['femme', 'amber', 'floral'],
    price: 21000,
    priceFormatted: '21 000 DA',
    volume: '80ml Eau de Parfum Rouge',
    badge: 'Sensualité Brûlante',
    rating: '4.9',
    reviewsCount: 220,
    desc: "L'attraction de l'interdit poussée à l'obsession. Une tubéreuse blanche charnelle enflammée par une orange sanguine ardente et un accord épicé rouge.",
    story: "L'audace de franchir la ligne rouge. Une sensualité incandescente qui consume tout sur son passage.",
    img: '/img/perfumes/ruby.webp',
    top: 'Orange Sanguine de Sicile, Gingembre Rouge',
    heart: 'Tubéreuse d’Inde, Jasmin Sambac, Piment Doux',
    base: 'Patchouli d’Indonésie, Bois de Santal, Vétiver',
    longevity: '48h',
    sillage: 'Incandescent & Fatal',
    concentration: 'Eau de Parfum Rouge'
  },
  {
    id: 14,
    name: "Givenchy L'Interdit Rouge Ultime",
    brand: 'Givenchy',
    gender: 'femme',
    category: 'amber',
    catLabels: ['femme', 'amber', 'gourmand'],
    price: 22500,
    priceFormatted: '22 500 DA',
    volume: '80ml Eau de Parfum Ultime',
    badge: 'Ultime Réserve',
    rating: '5.0',
    reviewsCount: 94,
    desc: "Le summum du magnétisme. L'accord floral blanc iconique s'enveloppe de coques de cacao recyclées et d'un patchouli sombre d'une richesse infinie.",
    story: "L'ultime tentation où la fleur blanche charnelle s'unit à la gourmandise sombre du cacao torréfié.",
    img: '/img/perfumes/ruby.webp',
    top: 'Fleur d’Oranger de Tunisie, Coques de Cacao Torréfié',
    heart: 'Tubéreuse Sombre, Jasmin Grandiflorum',
    base: 'Patchouli Cacao, Ambroxan, Vétiver Bourbon',
    longevity: '48h+',
    sillage: 'Addiction Sombre',
    concentration: 'Eau de Parfum Ultime'
  },
  {
    id: 15,
    name: 'Givenchy Irrésistible',
    brand: 'Givenchy',
    gender: 'femme',
    category: 'floral',
    catLabels: ['femme', 'floral', 'fresh'],
    price: 20800,
    priceFormatted: '20 800 DA',
    volume: '80ml Eau de Parfum',
    badge: 'Féminité Radieuse',
    rating: '4.8',
    reviewsCount: 140,
    desc: "Une invitation magnétique au lâcher-prise. Une rose antimorose ultra-lumineuse qui danse avec un bois blond éclatant et une poire délicieusement juteuse.",
    story: "Une bouffée d'énergie joyeuse pour celles qui s'expriment librement et avec élégance.",
    img: '/img/perfumes/rose.webp',
    top: 'Poire Sucrée, Ambrette d’Équateur',
    heart: 'Rose Essential Grasse, Iris Précieux',
    base: 'Bois de Cèdre de Virginie, Muscs Blancs',
    longevity: '36h',
    sillage: 'Radieux & Dansant',
    concentration: 'Eau de Parfum'
  },
  {
    id: 16,
    name: "Dior J'adore Intense",
    brand: 'Christian Dior',
    gender: 'femme',
    category: 'floral',
    catLabels: ['femme', 'floral', 'amber'],
    price: 29000,
    priceFormatted: '29 000 DA',
    volume: '100ml Eau de Parfum Intense',
    badge: 'Haute Parfumerie',
    rating: '5.0',
    reviewsCount: 340,
    desc: "L'or liquide de la Maison Dior. Un bouquet floral magistral composé d'absolus de fleur d'oranger, de jasmin de Grasse et de rose centifolia.",
    story: "Le chef-d'œuvre de la parfumerie Dior composé comme une ode à la féminité majestueuse.",
    img: '/img/perfumes/amber.webp',
    top: 'Fleur d’Oranger Solaire, Ylang-Ylang des Comores',
    heart: 'Jasmin Grandiflorum de Grasse, Rose de Mai',
    base: 'Bois de Santal Onctueux, Vanille d’Or',
    longevity: '48h',
    sillage: 'Impérial & Solaire',
    concentration: 'Eau de Parfum Intense'
  },
  {
    id: 17,
    name: 'Jean Paul Gaultier Divine Couture',
    brand: 'Jean Paul Gaultier',
    gender: 'femme',
    category: 'gourmand',
    catLabels: ['femme', 'gourmand', 'floral'],
    price: 23800,
    priceFormatted: '23 800 DA',
    volume: '100ml Eau de Parfum',
    badge: 'Couture Divine',
    rating: '4.9',
    reviewsCount: 155,
    desc: "Un hommage éclatant à toutes les femmes divines. Une alliance spectaculaire de lys blanc majestueux, de meringue gourmande et d'un souffle marin salé unique.",
    story: "Le corset iconique de Gaultier transformé en un bijou d'or pour une fragrance sensationnelle et salée-sucrée.",
    img: '/img/perfumes/ruby.webp',
    top: 'Calypso Marin, Bergamote, Fruits Rouges',
    heart: 'Lys Majestueux, Jasmin Étoilé, Ylang-Ylang',
    base: 'Meringue Sucrée, Musc Blanc, Patchouli Doré',
    longevity: '48h',
    sillage: 'Divin & Sucré-Salé',
    concentration: 'Eau de Parfum'
  },
  {
    id: 18,
    name: "L'Instant de Guerlain Femme",
    brand: 'Guerlain',
    gender: 'femme',
    category: 'amber',
    catLabels: ['femme', 'amber', 'floral'],
    price: 13900,
    priceFormatted: '13 900 DA',
    volume: '75ml Eau de Parfum',
    badge: 'Trésor Guerlain',
    rating: '4.8',
    reviewsCount: 96,
    desc: "L'instant où tout peut basculer dans la passion. Un miel d'agrumes lumineux se fond dans un magnolia opulent et un sillage d'ambre cristallin.",
    story: "Créé par la plus ancienne maison de parfum au monde, un moment d'émotion pure figé dans le temps.",
    img: '/img/perfumes/amber.webp',
    top: 'Miel d’Agrumes, Bergamote, Mandarine',
    heart: 'Magnolia Blanc, Ylang-Ylang, Jasmin Sambac',
    base: 'Ambre Cristallin, Benjoin, Bois de Santal',
    longevity: '36h',
    sillage: 'Raffiné & Chaleureux',
    concentration: 'Eau de Parfum'
  },
  {
    id: 19,
    name: "Dolce & Gabbana L'Impératrice",
    brand: 'Dolce & Gabbana',
    gender: 'femme',
    category: 'fresh',
    catLabels: ['femme', 'fresh', 'floral'],
    price: 9800,
    priceFormatted: '9 800 DA',
    volume: '100ml Eau de Toilette',
    badge: 'Best Value',
    rating: '4.8',
    reviewsCount: 280,
    desc: "Une explosion fruitée et magnétique qui captive instantanément. Pastèque succulente, kiwi exotique et cyclamen rose sur fond de muscs veloutés.",
    story: "Inspiré de la carte de tarot de L'Impératrice, symbole de séduction irrésistible et de vitalité.",
    img: '/img/perfumes/fresh.webp',
    top: 'Kiwi Juteux, Rhubarbe Rose, Poivre Rose',
    heart: 'Pastèque Gorgée d’Eau, Cyclamen Rose, Jasmin',
    base: 'Bois de Citronnier, Musc Propre, Santal',
    longevity: '24h',
    sillage: 'Fruité & Exotique',
    concentration: 'Eau de Toilette'
  },
  {
    id: 20,
    name: 'Mademoiselle Rochas',
    brand: 'Rochas',
    gender: 'femme',
    category: 'floral',
    catLabels: ['femme', 'floral', 'gourmand'],
    price: 9800,
    priceFormatted: '9 800 DA',
    volume: '90ml Eau de Parfum',
    badge: 'Chic Parisien',
    rating: '4.7',
    reviewsCount: 75,
    desc: "L'incarnation de la jeune Parisienne pétillante et espiègle. Pomme d'amour croquante, rose délicate et fond de santal caressant.",
    story: "Le chic français sans effort, plein de charme, de malice et d'élégance naturelle.",
    img: '/img/perfumes/rose.webp',
    top: 'Pomme d’Amour, Cassis Noir, Feuilles de Lierre',
    heart: 'Rose Pétillante, Jasmin d’Égypte, Violette',
    base: 'Bois de Santal, Ambre Gris, Chantilly Musquée',
    longevity: '30h',
    sillage: 'Gourmand & Espiègle',
    concentration: 'Eau de Parfum'
  },
  {
    id: 21,
    name: 'Versace Dylan Blue Pour Femme',
    brand: 'Versace',
    gender: 'femme',
    category: 'fresh',
    catLabels: ['femme', 'fresh', 'floral'],
    price: 13500,
    priceFormatted: '13 500 DA',
    volume: '100ml Eau de Parfum',
    badge: 'Méditerranéen',
    rating: '4.8',
    reviewsCount: 168,
    desc: "Une force sensuelle et élégante inspirée des rivages méditerranéens. Sorbet cassis rafraîchissant, pomme Granny Smith et bois blancs soyeux.",
    story: "Un hommage à la féminité puissante selon Donatella Versace, entre fraîcheur aquatique et sensualité boisée.",
    img: '/img/perfumes/fresh.webp',
    top: 'Sorbet Cassis Noir, Pomme Granny Smith, Trèfle',
    heart: 'Églantine Sauvage, Pêche Givrée, Pétalia, Jasmin',
    base: 'Styrax, Bois Blancs Précieux, Musc, Patchouli',
    longevity: '36h',
    sillage: 'Sensuel & Marin',
    concentration: 'Eau de Parfum'
  },

  // ─── HOMME & BOISÉS / ÉPICÉS / ORIENTAUX ───
  {
    id: 22,
    name: 'Emporio Armani Stronger With You (You Powerfully)',
    brand: 'Giorgio Armani',
    gender: 'homme',
    category: 'amber',
    catLabels: ['homme', 'amber', 'woody'],
    price: 21000,
    priceFormatted: '21 000 DA',
    volume: '100ml Eau de Parfum',
    badge: 'Charisme Pur',
    rating: '4.9',
    reviewsCount: 260,
    desc: "L'énergie masculine affirmée et séduisante. Cardamome épicée, poivre rose vibrant et un accord inimitable de marron glacé fumé à la vanille.",
    story: "L'histoire d'un amour puissant et inconditionnel, célébrant la confiance et le magnétisme contemporain.",
    img: '/img/perfumes/amber.webp',
    top: 'Cardamome du Guatemala, Poivre Rose, Violette',
    heart: 'Sauge Sclarée Aromatique, Lavande de Provence',
    base: 'Accord Marron Glacé, Vanille Jungle Essence, Cèdre',
    longevity: '48h',
    sillage: 'Chaud & Addictif',
    concentration: 'Eau de Parfum'
  },
  {
    id: 23,
    name: 'Givenchy Gentleman Society Ambrée',
    brand: 'Givenchy',
    gender: 'homme',
    category: 'amber',
    catLabels: ['homme', 'amber', 'woody'],
    price: 20500,
    priceFormatted: '20 500 DA',
    volume: '100ml Eau de Parfum Extrême',
    badge: 'Prestige',
    rating: '4.9',
    reviewsCount: 115,
    desc: "Rejoignez l'élite olfactive. Un accord inédit de narcisse sauvage couplé à un quatuor de vétivers nobles et une vanille Tasuki d'une profondeur absolue.",
    story: "Pour les hommes d'honneur qui définissent leurs propres règles avec distinction et savoir-être.",
    img: '/img/perfumes/emerald.webp',
    top: 'Sauge Sclarée, Noix de Muscade, Cardamome',
    heart: 'Narcisse Sauvage de France, Café Torréfié, Iris',
    base: 'Quatuor de Vétivers, Vanille Tasuki, Cèdre',
    longevity: '48h',
    sillage: 'Aristocratique',
    concentration: 'Eau de Parfum Extrême'
  },
  {
    id: 24,
    name: 'Jean Paul Gaultier Scandal Pour Homme Elixir',
    brand: 'Jean Paul Gaultier',
    gender: 'homme',
    category: 'gourmand',
    catLabels: ['homme', 'gourmand', 'amber'],
    price: 23500,
    priceFormatted: '23 500 DA',
    volume: '100ml Parfum Concentré',
    badge: 'Coup de Poing',
    rating: '5.0',
    reviewsCount: 190,
    desc: "Le roi du ring olfactif. Un caramel brûlé au beurre salé percutant mêlé à la fève tonka suave et un vétiver puissant qui fait succomber les foules.",
    story: "Couronné champion de la séduction, ce concentré d'audace frappe avec force et volupté.",
    img: '/img/perfumes/oud.webp',
    top: 'Sauge Royale, Mandarine Sanguine',
    heart: 'Caramel Salé Onctueux, Fève Tonka Intense',
    base: 'Vétiver Sombre, Cèdre Noir',
    longevity: '48h+',
    sillage: 'Dévastateur & Gourmand',
    concentration: 'Parfum Concentré'
  },
  {
    id: 25,
    name: "Prada Paradigme / L'Homme",
    brand: 'Prada',
    gender: 'homme',
    category: 'woody',
    catLabels: ['homme', 'woody', 'fresh'],
    price: 21800,
    priceFormatted: '21 800 DA',
    volume: '100ml Eau de Toilette Haute',
    badge: 'Signature Chic',
    rating: '4.9',
    reviewsCount: 145,
    desc: "La perfection architecturale en flacon. Un iris noble majestueux marié au néroli lumineux et à l'ambre chaud pour une allure aristocratique impeccable.",
    story: "L'exploration de la dualité masculine selon Miuccia Prada, épurée, sophistiquée et luxueuse.",
    img: '/img/perfumes/emerald.webp',
    top: 'Néroli Doré, Poivre Noir, Cardamome',
    heart: 'Iris Pallida d’Italie, Violette, Géranium',
    base: 'Ambre Chaud, Bois de Cèdre, Patchouli Pur',
    longevity: '36h',
    sillage: 'Raffinement Absolu',
    concentration: 'Eau de Toilette Haute'
  },
  {
    id: 26,
    name: 'Montblanc Explorer Platinum / Extrême',
    brand: 'Montblanc',
    gender: 'homme',
    category: 'woody',
    catLabels: ['homme', 'woody', 'fresh'],
    price: 12800,
    priceFormatted: '12 800 DA',
    volume: '100ml Eau de Parfum',
    badge: 'Aventure',
    rating: '4.8',
    reviewsCount: 130,
    desc: "L'appel des sommets glaciaires. Pamplemousse givré, sauge aromatique vivifiante et cèdre majestueux composent une ode à la conquête.",
    story: "Inspiré par les expéditions vers les sommets les plus vertigineux du mont Blanc.",
    img: '/img/perfumes/emerald.webp',
    top: 'Pamplemousse Givré, Feuilles de Violette',
    heart: 'Sauge Sclarée Pure, Poivre Rose Alpin',
    base: 'Bois de Cèdre Platinum, Ambre Minéral',
    longevity: '36h',
    sillage: 'Vibrant & Frais',
    concentration: 'Eau de Parfum'
  },
  {
    id: 27,
    name: "Hermès Terre d'Hermès Intense",
    brand: 'Hermès',
    gender: 'homme',
    category: 'woody',
    catLabels: ['homme', 'woody', 'fresh'],
    price: 18800,
    priceFormatted: '18 800 DA',
    volume: '100ml Eau Intense Vétiver',
    badge: 'Légende',
    rating: '5.0',
    reviewsCount: 380,
    desc: "La force minérale et tellurique portée à incandescence. La puissance du vétiver haïtien sublimée par des agrumes solaires et du poivre du Sichuan.",
    story: "La structure originelle de Terre d'Hermès revisitée par Christine Nagel, où le vétiver prend racine dans une terre fertile et chaude.",
    img: '/img/perfumes/emerald.webp',
    top: 'Bergamote Verte, Pamplemousse Hespéridé',
    heart: 'Poivre du Sichuan, Géranium Sauvage, Silex Minéral',
    base: 'Vétiver Intense d’Haïti, Résine d’Oliban, Cèdre',
    longevity: '48h',
    sillage: 'Noble & Tellurique',
    concentration: 'Eau Intense'
  },
  {
    id: 28,
    name: 'Giorgio Armani Acqua Di Giò Eau de Parfum',
    brand: 'Giorgio Armani',
    gender: 'homme',
    category: 'fresh',
    catLabels: ['homme', 'fresh', 'woody'],
    price: 18800,
    priceFormatted: '18 800 DA',
    volume: '100ml Eau de Parfum',
    badge: 'Indétrônable',
    rating: '4.9',
    reviewsCount: 450,
    desc: "L'immensité de la mer Méditerranée encapsulée. Des notes marines cristallines vivifiées par la mandarine verte de Calabre et un patchouli guatémaltèque durable.",
    story: "L'île de Pantelleria et ses roches volcaniques léchées par des vagues turquoise, un souffle de liberté absolue.",
    img: '/img/perfumes/fresh.webp',
    top: 'Notes Marines Océaniques, Mandarine Verte',
    heart: 'Sauge Sclarée, Lavande de Provence, Géranium',
    base: 'Patchouli du Guatemala, Vétiver Minéral',
    longevity: '36h',
    sillage: 'Océanique & Magnétique',
    concentration: 'Eau de Parfum'
  },
  {
    id: 29,
    name: 'Givenchy Gentleman Eau de Parfum',
    brand: 'Givenchy',
    gender: 'homme',
    category: 'woody',
    catLabels: ['homme', 'woody', 'amber'],
    price: 16200,
    priceFormatted: '16 200 DA',
    volume: '100ml Eau de Parfum',
    badge: 'Gentleman Noir',
    rating: '4.9',
    reviewsCount: 180,
    desc: "Le charme nocturne à l'état pur. Un iris précieux sombrement enveloppé de poivre noir, de baume de Tolu et de vanille noire de Madagascar.",
    story: "Pour l'homme raffiné dont l'élégance naturelle n'a besoin d'aucun artifice pour séduire.",
    img: '/img/perfumes/noir.webp',
    top: 'Poivre Noir de Madagascar, Bergamote, Lavande',
    heart: 'Iris d’Italie Sombre, Cannelle, Clou de Girofle',
    base: 'Vanille Noire, Baume de Tolu, Patchouli, Benjoin',
    longevity: '48h',
    sillage: 'Sombre & Velouté',
    concentration: 'Eau de Parfum'
  },
  {
    id: 30,
    name: 'Jean Paul Gaultier Le Beau Narcisse / Le Parfum',
    brand: 'Jean Paul Gaultier',
    gender: 'homme',
    category: 'woody',
    catLabels: ['homme', 'woody', 'gourmand'],
    price: 23500,
    priceFormatted: '23 500 DA',
    volume: '125ml Le Parfum Intense',
    badge: 'Séduction Solaire',
    rating: '4.9',
    reviewsCount: 225,
    desc: "Le fruit défendu du jardin d'Éden de Gaultier. Noix de coco sensuelle, bois de santal chaud et fève tonka addictive pour un sillage aphrodisiaque.",
    story: "Une tentation irrésistible sous le soleil d'un jardin tropical où tout est permis.",
    img: '/img/perfumes/amber.webp',
    top: 'Ananas Givré, Gingembre Sauvage, Cyprès',
    heart: 'Bois de Coco Grillé, Fève Tonka Suave',
    base: 'Bois de Santal Royal, Ambre Gris',
    longevity: '48h',
    sillage: 'Aphrodisiaque',
    concentration: 'Le Parfum Intense'
  },
  {
    id: 31,
    name: 'Paco Rabanne Invictus Victory Elixir',
    brand: 'Paco Rabanne',
    gender: 'homme',
    category: 'amber',
    catLabels: ['homme', 'amber', 'woody'],
    price: 22800,
    priceFormatted: '22 800 DA',
    volume: '100ml Parfum Intense',
    badge: 'Victoire Ultime',
    rating: '4.9',
    reviewsCount: 240,
    desc: "La quintessence de la puissance masculine. Un encens mystique associé à une vanille noire envoûtante et une fève tonka magnétique.",
    story: "La consécration de la victoire pour ceux qui ne reculent devant aucun défi.",
    img: '/img/perfumes/noir.webp',
    top: 'Cardamome Noire, Poivre Rose, Lavandin Vert',
    heart: 'Encens Mystique, Patchouli d’Indonésie',
    base: 'Gousse de Vanille Noire, Fève Tonka Sombre',
    longevity: '48h+',
    sillage: 'Triomphal & Puissant',
    concentration: 'Parfum Intense'
  },
  {
    id: 32,
    name: 'Yves Saint Laurent MYSLF Le Parfum',
    brand: 'Yves Saint Laurent',
    gender: 'homme',
    category: 'woody',
    catLabels: ['homme', 'woody', 'floral'],
    price: 23800,
    priceFormatted: '23 800 DA',
    volume: '100ml Le Parfum',
    badge: 'Haute Signature',
    rating: '5.0',
    reviewsCount: 165,
    desc: "L'affirmation audacieuse de l'homme contemporain. Une fleur d'oranger intense et texturée, intensifiée par des bois noirs et un accord poivré vibrant.",
    story: "Être soi-même sans compromis. L'intensité masculine d'une génération libre et passionnée.",
    img: '/img/perfumes/noir.webp',
    top: 'Poivre Noir Vibrant, Bergamote de Calabre',
    heart: 'Fleur d’Oranger Intense de Tunisie',
    base: 'Bois Riches Ambrés, Patchouli Cœur, Vanille Bourbon',
    longevity: '48h',
    sillage: 'Moderne & Noir',
    concentration: 'Le Parfum'
  },
  {
    id: 33,
    name: 'Yves Saint Laurent MYSLF Eau de Parfum',
    brand: 'Yves Saint Laurent',
    gender: 'homme',
    category: 'woody',
    catLabels: ['homme', 'woody', 'fresh'],
    price: 20500,
    priceFormatted: '20 500 DA',
    volume: '100ml Eau de Parfum',
    badge: 'Modernité',
    rating: '4.9',
    reviewsCount: 290,
    desc: "La nouvelle icône masculine signée YSL. Une fraîcheur éclatante de bergamote combinée à un cœur floral pur et des bois sensuels.",
    story: "La réinvention de la masculinité dans un sillage fluide et infiniment raffiné.",
    img: '/img/perfumes/oud.webp',
    top: 'Cœur de Bergamote de Calabre, Vert de Bergamote',
    heart: 'Absolu de Fleur d’Oranger de Tunisie',
    base: 'Cœur de Patchouli d’Indonésie, Ambrofix',
    longevity: '36h',
    sillage: 'Épuré & Sensuel',
    concentration: 'Eau de Parfum'
  },
  {
    id: 34,
    name: "Yves Saint Laurent La Nuit de L'Homme Eau de Parfum",
    brand: 'Yves Saint Laurent',
    gender: 'homme',
    category: 'amber',
    catLabels: ['homme', 'amber', 'woody'],
    price: 21000,
    priceFormatted: '21 000 DA',
    volume: '100ml Eau de Parfum',
    badge: 'Séducteur Nocturne',
    rating: '4.9',
    reviewsCount: 370,
    desc: "Le philtre de séduction le plus célèbre du monde. Cardamome orientale, bois de cèdre noble et fève tonka dans une concentration riche et envoûtante.",
    story: "Quand la nuit tombe sur Paris, l'homme YSL devient le maître irrésistible de toutes les attractions.",
    img: '/img/perfumes/noir.webp',
    top: 'Cardamome Aromatique, Pamplemousse',
    heart: 'Essence de Cèdre de Virginie, Sauge Sclarée',
    base: 'Fève Tonka Suave, Bois de Santal, Vétiver',
    longevity: '48h',
    sillage: 'Hypnotique',
    concentration: 'Eau de Parfum'
  },
  {
    id: 35,
    name: 'Montblanc Legend Elixir / Red',
    brand: 'Montblanc',
    gender: 'homme',
    category: 'woody',
    catLabels: ['homme', 'woody', 'fresh'],
    price: 13000,
    priceFormatted: '13 000 DA',
    volume: '100ml Eau de Parfum',
    badge: 'Intrépide',
    rating: '4.8',
    reviewsCount: 140,
    desc: "La passion et l'énergie à l'état pur. Une orange sanguine vive confrontée à la sauge aromatique et des bois d'acajou nobles.",
    story: "Le rouge symbolisant le courage, la détermination et la force des esprits pionniers.",
    img: '/img/perfumes/ruby.webp',
    top: 'Orange Sanguine Juteuse, Cardamome, Pamplemousse',
    heart: 'Sauge Aromatique, Bois de Cèdre, Baies de Genièvre',
    base: 'Bois d’Acajou Sombre, Fève Tonka, Cèdre de l’Atlas',
    longevity: '36h',
    sillage: 'Vigoureux',
    concentration: 'Eau de Parfum'
  },
  {
    id: 36,
    name: 'Lacoste L.12.12 Original Aqua',
    brand: 'Lacoste',
    gender: 'homme',
    category: 'fresh',
    catLabels: ['homme', 'fresh'],
    price: 11500,
    priceFormatted: '11 500 DA',
    volume: '100ml Eau de Toilette',
    badge: 'Fraîcheur Pure',
    rating: '4.7',
    reviewsCount: 85,
    desc: "L'énergie d'un plongeon en eaux claires. Pamplemousse rose étincelant, poivre rose piquant et accords aquatiques dynamisants.",
    story: "Inspiré par le polo iconique L.12.12 et la fraîcheur d'un court de tennis au lever du jour.",
    img: '/img/perfumes/fresh.webp',
    top: 'Pamplemousse Rose, Poivre Rose, Mandarine',
    heart: 'Accord Aquatique Cristallin, Sauge Sclarée',
    base: 'Bois de Cèdre, Vétiver Haïtien, Muscs Propres',
    longevity: '24h',
    sillage: 'Sport & Vivifiant',
    concentration: 'Eau de Toilette'
  },
  {
    id: 37,
    name: 'Kenzo Homme Indigo / Santal Marin',
    brand: 'Kenzo',
    gender: 'homme',
    category: 'woody',
    catLabels: ['homme', 'woody', 'fresh'],
    price: 12800,
    priceFormatted: '12 800 DA',
    volume: '110ml Eau de Parfum',
    badge: 'Poésie Océane',
    rating: '4.8',
    reviewsCount: 92,
    desc: "Une rencontre poétique entre la mer indomptée et le bois chauffé au soleil. Accords marins salés, cuir souple et santal apaisant.",
    story: "Le flacon bambou penché par le vent marin, sculpté comme une ode à la liberté naturelle.",
    img: '/img/perfumes/emerald.webp',
    top: 'Accords Marins Iodés, Poivre Rose, Cardamome',
    heart: 'Cuir Chaud, Figue Sauvage, Patchouli',
    base: 'Bois de Santal Doré, Akigalawood, Vétiver',
    longevity: '36h',
    sillage: 'Marin & Boisé',
    concentration: 'Eau de Parfum'
  },
  {
    id: 38,
    name: 'Dior Sauvage Le Parfum',
    brand: 'Christian Dior',
    gender: 'homme',
    category: 'amber',
    catLabels: ['homme', 'amber', 'woody'],
    price: 25800,
    priceFormatted: '25 800 DA',
    volume: '100ml Le Parfum',
    badge: 'Légende Dior',
    rating: '5.0',
    reviewsCount: 520,
    desc: "L'interprétation la plus dense et mystérieuse de Sauvage. Une mandarine juteuse et nocturne embrasée par un santal crémeux du Sri Lanka et une fève tonka fumée.",
    story: "L'heure bleue dans le désert où le ciel s'embrase et libère la magie des grands espaces sauvages.",
    img: '/img/perfumes/noir.webp',
    top: 'Mandarine Sauvage, Bergamote de Reggio',
    heart: 'Bois de Santal du Sri Lanka, Cèdre de Virginie',
    base: 'Fève Tonka Noire, Absolu de Vanille Papouasie',
    longevity: '48h+',
    sillage: 'Monumental',
    concentration: 'Le Parfum'
  },
  {
    id: 39,
    name: 'Dior Sauvage Elixir 100ml',
    brand: 'Christian Dior',
    gender: 'homme',
    category: 'woody',
    catLabels: ['homme', 'woody', 'amber'],
    price: 39000,
    priceFormatted: '39 000 DA',
    volume: '100ml Elixir Concentré',
    badge: 'Chef-d’Œuvre',
    rating: '5.0',
    reviewsCount: 680,
    desc: "La quintessence absolue de la parfumerie masculine. Une concentration sans précédent où des épices enivrantes rencontrent une lavande de Nyons sur mesure et des bois profonds.",
    story: "Composé par François Demachy comme une liqueur rare de haute précision, d'une puissance et d'une noblesse incomparables.",
    img: '/img/perfumes/noir.webp',
    top: 'Cannelle Royale, Noix de Muscade, Cardamome, Pamplemousse',
    heart: 'Cœur de Lavande de Nyons AOP',
    base: 'Bois de Réglisse Sombre, Santal, Ambre, Patchouli',
    longevity: '72h',
    sillage: 'Légendaire & Infini',
    concentration: 'Elixir Concentré (35%)'
  },
  {
    id: 40,
    name: 'Dolce & Gabbana K (King) 200ml Eau de Parfum',
    brand: 'Dolce & Gabbana',
    gender: 'homme',
    category: 'woody',
    catLabels: ['homme', 'woody', 'fresh'],
    price: 18500,
    priceFormatted: '18 500 DA',
    volume: '200ml Format XXL King',
    badge: 'Format XXL (200ml)',
    rating: '4.8',
    reviewsCount: 160,
    desc: "Le parfum de l'homme qui règne sur son quotidien. Orange sanguine explosive, essence de piment fort épicé et cèdre noble de l'Atlas.",
    story: "Couronné par un bouchon artisanal en forme de couronne royale, pour les souverains du quotidien.",
    img: '/img/perfumes/oud.webp',
    top: 'Orange Sanguine de Sicile, Citron Torréfié, Genièvre',
    heart: 'Essence de Piment Fort, Lavande, Sauge Sclarée',
    base: 'Bois de Cèdre de l’Atlas, Patchouli, Vétiver',
    longevity: '36h',
    sillage: 'Royal & Conquérant',
    concentration: 'Eau de Parfum'
  },
  {
    id: 41,
    name: 'Lacoste Booster',
    brand: 'Lacoste',
    gender: 'homme',
    category: 'fresh',
    catLabels: ['homme', 'fresh'],
    price: 9200,
    priceFormatted: '9 200 DA',
    volume: '125ml Eau de Toilette',
    badge: 'Énergie Pure',
    rating: '4.7',
    reviewsCount: 95,
    desc: "Le coup de fouet tonique légendaire. Menthe poivrée vivifiante, eucalyptus rafraîchissant et vétiver énergisant pour les esprits sportifs.",
    story: "La fraîcheur aromatique vintage indémodable qui réveille les sens dès le matin.",
    img: '/img/perfumes/emerald.webp',
    top: 'Menthe Poivrée, Eucalyptus, Orange d’Italie',
    heart: 'Lavande, Basilic Aromatique, Noix de Muscade',
    base: 'Vétiver, Bois de Cèdre, Santal Blanc',
    longevity: '24h',
    sillage: 'Tonique & Vivifiant',
    concentration: 'Eau de Toilette'
  },
  {
    id: 42,
    name: 'Dolce & Gabbana The One Eau de Parfum Intense',
    brand: 'Dolce & Gabbana',
    gender: 'homme',
    category: 'amber',
    catLabels: ['homme', 'amber', 'woody'],
    price: 14500,
    priceFormatted: '14 500 DA',
    volume: '100ml Eau de Parfum Intense',
    badge: 'Élégance Noire',
    rating: '4.9',
    reviewsCount: 230,
    desc: "Le magnétisme obscur d'un smoking impeccable. Néroli doré, cardamome envoûtante et cuir noir fumé composent un sillage de haute séduction.",
    story: "L'incarnation de l'homme sophistiqué dont le regard capte l'attention de toute une assemblée.",
    img: '/img/perfumes/noir.webp',
    top: 'Néroli Doré, Cardamome, Cyprès Frais',
    heart: 'Benjoin Chaud, Sauge Sclarée, Muscade',
    base: 'Cuir Noir Profond, Patchouli Sombre, Ciste',
    longevity: '48h',
    sillage: 'Cuiré & Magnétique',
    concentration: 'Eau de Parfum Intense'
  },
  {
    id: 43,
    name: 'Jean Paul Gaultier Scandal Absolu',
    brand: 'Jean Paul Gaultier',
    gender: 'unisexe',
    category: 'amber',
    catLabels: ['unisexe', 'amber', 'gourmand'],
    price: 20500,
    priceFormatted: '20 500 DA',
    volume: '100ml Concentré Absolu',
    badge: 'Scandale Absolu',
    rating: '4.9',
    reviewsCount: 175,
    desc: "L'audace portée à son comble. Une tubéreuse opulente embrasse une figue noire gourmande et un bois de santal d'une richesse stupéfiante.",
    story: "Un parfum libre et décomplexé sans distinction de genre, pour les amateurs d'excès assumés.",
    img: '/img/perfumes/ruby.webp',
    top: 'Figue Noire Gourmande, Mandarine Dorée',
    heart: 'Tubéreuse Opulente, Fleur d’Oranger Solaire',
    base: 'Bois de Santal Crémeux, Ambre Chaud',
    longevity: '48h',
    sillage: 'Opulent & Envoûtant',
    concentration: 'Concentré Absolu'
  },
  {
    id: 44,
    name: 'Jean Paul Gaultier Scandal Intense 150ml',
    brand: 'Jean Paul Gaultier',
    gender: 'homme',
    category: 'gourmand',
    catLabels: ['homme', 'gourmand', 'amber'],
    price: 24800,
    priceFormatted: '24 800 DA',
    volume: '150ml Format Géant',
    badge: 'Format XXL (150ml)',
    rating: '5.0',
    reviewsCount: 195,
    desc: "L'addiction en format généreux. Caramel salé gourmand, fève tonka envoûtante et vétiver viril pour des mois de présence inoubliable.",
    story: "Le parfum de tous les succès dans un flacon géant de 150ml d'une générosité impériale.",
    img: '/img/perfumes/amber.webp',
    top: 'Sauge Sclarée Royale, Mandarine',
    heart: 'Caramel Doré Fumé, Fève Tonka',
    base: 'Vétiver Sombre, Cèdre Majestueux',
    longevity: '48h+',
    sillage: 'Puissant & XXL',
    concentration: 'Eau de Parfum Intense'
  },
  {
    id: 45,
    name: 'Azzaro Wanted by Night',
    brand: 'Azzaro',
    gender: 'homme',
    category: 'amber',
    catLabels: ['homme', 'amber', 'woody'],
    price: 14800,
    priceFormatted: '14 800 DA',
    volume: '100ml Eau de Parfum',
    badge: 'Nuit Blanche',
    rating: '4.8',
    reviewsCount: 210,
    desc: "L'arme de séduction des créatures nocturnes. Cannelle chaude, cèdre rouge de Virginie et tabac blond envoûtant composent une aura incandescente.",
    story: "Créé pour l'homme de la nuit qui vit intensément et transforme chaque soirée en fête mémorable.",
    img: '/img/perfumes/noir.webp',
    top: 'Cannelle Jaune, Mandarine Verte, Lavande',
    heart: 'Cèdre Rouge, Encens Mystique, Cumin',
    base: 'Tabac Blond de Virginie, Cyprès, Cuir',
    longevity: '48h',
    sillage: 'Chaud & Boisé',
    concentration: 'Eau de Parfum'
  }
];
